# Generated by Django 4.1.2 on 2022-12-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_cartitem_rename_seller_name_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
