# Generated by Django 4.1.2 on 2022-12-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
